# This is a basic workflow to help you get started with Actions

name: mod run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Download CLI"
          mvn -q dependency:copy -Dartifact=io.moderne:moderne-cli:2.5.9 -DoutputDirectory=.
          mv moderne-cli-*.jar mod.jar
          echo "Build LST"
          java -jar mod.jar build .
          echo "Install recipe"
          java -jar mod.jar config recipes jar install org.openrewrite:rewrite-core:LATEST || true
          echo "Echo log if exists"
          cat ~/.moderne/cli/recipes/*/recipes.log || true
          echo "Run recipe"
          java -jar mod.jar run . --recipe=FindCommitters